Adjustments
linagora/angular-translate-quality pull request #28
Opened 2017-04-27 15:42 UTC by dpoetzsch

First, thaks for the gread work.

However, to make it apply to our project and workflow we needed more configuration options. This PR handles these:

1. An option to ignore empty values
2. An option to ignore the order of keys
3. An optional specification of the indentation used in json files
4. Detection of invalid tabs in values
5. Tests & documentation for all of these

I think in the long run an integration of something like [jsonlint](https://github.com/zaach/jsonlint) would be a good idea and also solve issue #27 

If this is interesting to you maybe I could work smth out with jsonlint in the next weeks (depending how much time I can spare)

2017-04-27 16:01 UTC, vincent-zurczak commented
Hi! Thanks for this PR.
Overall, your upgrades seem correct to me. I will take a deeper look tomorrow and perform a code review.

2017-04-27 16:54 UTC, vincent-zurczak requested changes

2017-04-27 16:54 UTC, vincent-zurczak commented on lib/index.js
> +          'Values must not contain tabs (this is invalid json, escape them using \t). Key: ' + key, lineCpt);
"must not" => "cannot"

2017-04-27 16:54 UTC, vincent-zurczak commented on test/api.spec.js
> +    assert.include(errors[1], 'i18n keys must be sorted alphabetically. Key inv_key breaks this rule.');
Why was this test updated?
The default behavior should not have changed.

2017-04-27 16:54 UTC, vincent-zurczak commented on test/api.spec.js
> +    assert.equal(errors[0], '2: Values must not contain tabs (this is invalid json, escape them using \t). Key: BAZ');
"must not" => "cannot"

2017-04-27 16:54 UTC, vincent-zurczak commented on readme.md
> +Using this option this check can be deactivated. Default is `false`.
Just a detail, but add a comma after `Using this option`.

2017-04-27 16:54 UTC, vincent-zurczak commented on readme.md
> +* **ignore_empty_values**: Normally values should not be empty. Using this option this check can be deactivated.
Just a detail, but add a comma after `Using this option`.

2017-04-27 16:58 UTC, vincent-zurczak commented
OK. There are some little things. If you can fix them, I will merge your PR then. 👍 
If you have some time to work on json linting, your contribution will be welcome too.

2017-04-27 18:34 UTC, dpoetzsch commented on test/api.spec.js
> +    assert.include(errors[1], 'i18n keys must be sorted alphabetically. Key inv_key breaks this rule.');
for me, it was broken from the beginning

2017-04-27 18:41 UTC, dpoetzsch commented
I changed the mentioned things. Thanks for reviewing.

Still, I think "must not" is more apt as technically the values /can/ contain tabs, but they are not allowed to. However, your project, your rules :)

2017-04-28 07:40 UTC, vincent-zurczak commented on test/api.spec.js
> +    assert.include(errors[1], 'i18n keys must be sorted alphabetically. Key inv_key breaks this rule.');
OK, I will check this later.

2017-04-28 07:48 UTC, vincent-zurczak commented
So, maybe "should not" is better. I will fix it later.
The weird stuff is that tests are marked as successful while there is one failure. I created [an issue](https://github.com/linagora/angular-translate-quality/issues/29) about it.

See https://travis-ci.org/linagora/angular-translate-quality/builds/226516806
I guess this is the "inv_key" thing. Previous tests were all working: https://travis-ci.org/linagora/angular-translate-quality/builds/196362883

2017-04-28 09:30 UTC, dpoetzsch commented
I can revert that "fix" of the test. However, for me locally it is broken then.

2017-04-28 11:18 UTC, vincent-zurczak commented
Wait... I have taken a moment to investigate it. And you are right. The test was wrong.  :dizzy_face:
`i` comes before `k`. So, inv_key is the wrongly located key.

However, the previous test worked on my machine and on Travis. Looking at the code, I thought it might be an issue related to the localeCompare function. And indeed, there is a case-sensitive issue.

So, I am going to merge your PR.
I will also fix #29 and #30. And then, I will release a new version of the library on NPM.

Thank you for your help. :+1:

2017-04-28 11:19 UTC, merged